### ISSUE TITLE
Commit working examples

### ISSUE THREAD

**Issue by vtsatskin** [Erik-J-D/sydetex#3]

**Comment by Erik-J-D** [comment]
There are already 2 working examples... they just suck. I'll improve them at some point then close this.

**Comment by vtsatskin** [comment]
I meant to commit the generated PDFs so people can quickly see what the
template is.

On Thu, Feb 4, 2016, 4:53 PM Erik Derohanian notifications@github.com
wrote:

> There are already 2 working examples... they just suck. I'll improve them
> at some point then close this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Erik-J-D/sydetex/issues/3#issuecomment-180068053.
> 
> ## 

Sent from my device tracking my every move,

vt
