### ISSUE TITLE
Reference page incorrectly citing misc reference

### ISSUE THREAD

**Issue by bcaldwell** [Erik-J-D/sydetex#8]
example:
![14349172_10202233907806409_11899943_n png](https://cloud.githubusercontent.com/assets/8838361/18587001/bc313496-7bed-11e6-8303-fc63fcb0e4c5.jpeg)
should be 
![14355947_1800784840198250_94732294_n png](https://cloud.githubusercontent.com/assets/8838361/18586997/b9a7ae26-7bed-11e6-97cb-97e0cef4378d.jpeg)

I could be wrong here, but its missing the url....

**Comment by bcaldwell** [comment]
Perhaps it would be as easy as changing to `\bibliographystyle{IEEEtran}` instead of `\bibliographystyle{unsrt}`

**Comment by nolan-cerebras** [comment]
definitely agree that the urls need to display in the bib, only problem is the giant spacing inbetween stuff. Perhaps it is because the bib is defaulting to justified text... will investigate

**Comment by bcaldwell** [comment]
I see what youre saying. The standard looks like its left justified. You could do:

```
    \begingroup
        \raggedright
        \bibliography{references}
    \endgroup
```

**Comment by nolan-cerebras** [comment]
@benjamincaldwell done in https://github.com/Erik-J-D/sydetex/pull/10

**Comment by ndey96** [comment]
@Erik-J-D this issue will be fixed once https://github.com/Erik-J-D/sydetex/pull/10 gets merged
